package EjerciciosUnidad3;

public class Control extends javax.swing.JFrame {

	public int IncX=1;   
	public int IncY=1;     
	public boolean salir = false; 
    /**
     * Creates new form Control
     */
    public Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Disminuir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Aumentar = new javax.swing.JButton();
        Suspender = new javax.swing.JButton();
        Terminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Disminuir.setText("Disminuir");
        Disminuir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisminuirActionPerformed(evt);
            }
        });

        jLabel1.setText("Control de Hilos");

        Aumentar.setText("Aumentar");
        Aumentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AumentarActionPerformed(evt);
            }
        });

        Suspender.setText("Suspender");
        Suspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuspenderActionPerformed(evt);
            }
        });

        Terminar.setText("Terminar");
        Terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Terminar)
                    .addComponent(Suspender)
                    .addComponent(Aumentar)
                    .addComponent(jLabel1)
                    .addComponent(Disminuir))
                .addGap(162, 162, 162))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(Disminuir)
                .addGap(42, 42, 42)
                .addComponent(Aumentar)
                .addGap(39, 39, 39)
                .addComponent(Suspender)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(Terminar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void DisminuirActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        IncX-=1;         
        IncY-=1;        
        if (IncX < -10) IncX = -10;         
        if (IncY < -10) IncY = -10;
    	
    }                                        

    private void AumentarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	 IncX+=1;      
    	 IncY+=1; 
    	 if (IncX > 10) IncX = 10;     
    	 if (IncY > 10) IncY = 10; 
    }                                        

    private void SuspenderActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	IncX=0;         
    	IncY=0; 
    
    }                                        

    @SuppressWarnings("unused")
	private void TerminarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	salir=true;
    } 
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Control.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Control().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
 
		    // Variables declaration - do not modify                     
		    private javax.swing.JButton Disminuir;
		    private javax.swing.JButton Aumentar;
		    private javax.swing.JButton Suspender;
		    private javax.swing.JButton Terminar;
		    private javax.swing.JLabel jLabel1;
		    // End of variables declaration                   
		}

